In [2]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("drugs_for_common_treatments.csv")

In [15]:
filter_otc = data['rx_otc'] == 'OTC'
data_otc = data[filter_otc]

data_otc

,drug_name,medical_condition,medical_condition_description,activity,rx_otc,pregnancy_category,csa,alcohol,rating,no_of_reviews,medical_condition_url,drug_link
76,Acne Treatment,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,1%,OTC,C,N,NaN,NaN,NaN,https://www.drugs.com/condition/acne.html,https://www.drugs.com/cdi/acne-treatment.html
100,PanOxyl,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,1%,OTC,C,N,NaN,8.5,6.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/mtm/panoxyl.html
101,PanOxyl 10% Acne Foaming Wash,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,1%,OTC,C,N,NaN,9.5,2.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/cdi/panoxyl-wash.html
112,Acne-10,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,0%,OTC,C,N,NaN,NaN,NaN,https://www.drugs.com/condition/acne.html,https://www.drugs.com/cons/acne-10-gel-topical...
115,Acnomel,Acne,Acne Other names: Acne Vulgaris; Blackheads; B...,0%,OTC,N,N,NaN,5.0,1.0,https://www.drugs.com/condition/acne.html,https://www.drugs.com/cons/acnomel-skin-tone-t...
...,...,...,...,...,...,...,...,...,...,...,...,...
3619,Asper-Flex,Rheumatoid Arthritis,Rheumatoid Arthritis Other names: Arthritis; A...,0%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/rheumatoid-art...,https://www.drugs.com/cdi/asper-flex.html
3623,camphor / menthol / methyl salicylate,Rheumatoid Arthritis,Rheumatoid Arthritis Other names: Arthritis; A...,0%,OTC,NaN,N,NaN,9.0,1.0,https://www.drugs.com/condition/rheumatoid-art...,https://www.drugs.com/mtm/camphor-menthol-and-...
3654,Myoflex,Rheumatoid Arthritis,Rheumatoid Arthritis Other names: Arthritis; A...,0%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/rheumatoid-art...,https://www.drugs.com/cdi/myoflex.html
3665,trolamine salicylate,Rheumatoid Arthritis,Rheumatoid Arthritis Other names: Arthritis; A...,0%,OTC,N,N,NaN,5.0,5.0,https://www.drugs.com/condition/rheumatoid-art...,https://www.drugs.com/cdi/trolamine-cream-and-...
3929,Alli,Weight Loss,Weight Loss (Obesity/Overweight) More than hal...,18%,OTC,X,N,NaN,6.0,109.0,https://www.drugs.com/condition/obesity.html,https://www.drugs.com/alli.html

In [19]:
filter_preg = data['pregnancy_category'] == 'B'
data_preg = data_otc[filter_preg]
data_preg

/var/folders/kj/8ccbfhn56tgcwgc45d118plh0000gn/T/ipykernel_3419/34412887.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data_preg = data_otc[filter_preg]

,drug_name,medical_condition,medical_condition_description,activity,rx_otc,pregnancy_category,csa,alcohol,rating,no_of_reviews,medical_condition_url,drug_link
1080,Dulcolax,Constipation,Constipation Other names: Difficulty passing s...,45%,OTC,B,N,NaN,5.2,960.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/dulcolax.html
1081,bisacodyl,Constipation,Constipation Other names: Difficulty passing s...,32%,OTC,B,N,NaN,5.2,1357.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/bisacodyl-oral-and-r...
1099,Bisa-Lax,Constipation,Constipation Other names: Difficulty passing s...,5%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/cdi/bisa-lax.html
1102,Correctol,Constipation,Constipation Other names: Difficulty passing s...,5%,OTC,B,N,NaN,5.3,36.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/cdi/correctol.html
1104,Fleet Bisacodyl,Constipation,Constipation Other names: Difficulty passing s...,5%,OTC,B,N,NaN,10.0,1.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/cdi/fleet-bisacodyl-enem...
1325,Humulin N,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",11%,OTC,B,N,X,10.0,1.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/humulin_n.html
1326,Humulin R,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",10%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/humulin-r.html
1328,Novolin R,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",9%,OTC,B,N,X,6.5,3.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/novolin-r.html
1330,Humulin 70/30,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",8%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/humulin_70-30.html
1332,Novolin N,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",8%,OTC,B,N,X,0.0,1.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/novolin-n.html
1335,Novolin 70/30,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",6%,OTC,B,N,X,10.0,1.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/novolin-70-30.html
1347,insulin isophane,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",3%,OTC,B,N,X,10.0,4.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/insulin-isophane.html
1349,Humulin N Pen,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",2%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/humulin-n-kwikpen.html
1352,insulin isophane / insulin regular,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",2%,OTC,B,N,X,9.3,3.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/insulin-isophane-and...
1361,Humulin 50/50,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",0%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/cons/humulin-50-50.html
1362,Humulin 70/30 Pen,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",0%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/humulin-70-30-kwikpe...
1363,ReliOn/Novolin 70/30,Diabetes (Type 1),"Diabetes, Type 1 Other names: Insulin Dependen...",0%,OTC,B,N,X,9.0,1.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/relion-novolin-70-30...
1416,Humulin R,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",3%,OTC,B,N,X,9.0,1.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/humulin-r.html
1426,Humulin N,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",2%,OTC,B,N,X,9.0,2.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/humulin_n.html
1446,Humulin 70/30,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",1%,OTC,B,N,X,6.0,1.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/humulin_70-30.html
1455,Novolin 70/30,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",1%,OTC,B,N,X,7.7,3.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/novolin-70-30.html
1456,Novolin N,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",1%,OTC,B,N,X,7.8,6.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/novolin-n.html
1457,Novolin R,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",1%,OTC,B,N,X,9.0,3.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/novolin-r.html
1486,Humulin 50/50,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",0%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/cons/humulin-50-50.html
1487,Humulin 70/30 Pen,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",0%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/humulin-70-30-kwikpe...
1488,Humulin N Pen,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",0%,OTC,B,N,X,6.0,1.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/humulin-n-kwikpen.html
1495,insulin isophane / insulin regular,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",0%,OTC,B,N,X,7.3,4.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/insulin-isophane-and...
1496,insulin isophane,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",0%,OTC,B,N,X,7.3,10.0,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/insulin-isophane.html
1510,ReliOn/Novolin 70/30,Diabetes (Type 2),"Diabetes, Type 2 Other names: Diabetes; Nonins...",0%,OTC,B,N,X,NaN,NaN,https://www.drugs.com/condition/diabetes-melli...,https://www.drugs.com/mtm/relion-novolin-70-30...
1730,Pepcid AC,GERD (Heartburn),GERD Other names: Acid reflux; Esophageal Refl...,7%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/gastroesophage...,https://www.drugs.com/cons/pepcid-ac.html
1734,Acid Controller Maximum Strength,GERD (Heartburn),GERD Other names: Acid reflux; Esophageal Refl...,4%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/gastroesophage...,https://www.drugs.com/pro/berkley-and-jensen-a...
1735,Acid Controller Original Strength,GERD (Heartburn),GERD Other names: Acid reflux; Esophageal Refl...,4%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/gastroesophage...,https://www.drugs.com/pro/acid-controller-orig...
1739,Heartburn Relief,GERD (Heartburn),GERD Other names: Acid reflux; Esophageal Refl...,4%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/gastroesophage...,https://www.drugs.com/cons/heartburn-relief.html
1743,Pepcid AC Chewable Tablets,GERD (Heartburn),GERD Other names: Acid reflux; Esophageal Refl...,4%,OTC,B,N,NaN,10.0,1.0,https://www.drugs.com/condition/gastroesophage...,https://www.drugs.com/cdi/pepcid-ac-chewable-t...
1758,Prevacid OTC,GERD (Heartburn),GERD Other names: Acid reflux; Esophageal Refl...,1%,OTC,B,N,NaN,8.0,1.0,https://www.drugs.com/condition/gastroesophage...,https://www.drugs.com/mtm/prevacid-otc.html
1774,Axid AR,GERD (Heartburn),GERD Other names: Acid reflux; Esophageal Refl...,0%,OTC,B,N,NaN,10.0,2.0,https://www.drugs.com/condition/gastroesophage...,https://www.drugs.com/axid.html
1874,Claritin-D,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,2%,OTC,B,N,NaN,3.7,21.0,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/claritin-d.html
1875,Claritin-D 24 Hour,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,2%,OTC,B,N,NaN,4.7,6.0,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/claritin-d-24-hour.html
1885,Loratadine-D 24 Hour,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,2%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/loratadine-d-24-hour...
1915,Claritin-D 12 Hour,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,1%,OTC,B,N,NaN,1.7,3.0,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/claritin-d-12-hour.html
1926,loratadine / pseudoephedrine,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,1%,OTC,B,N,NaN,3.6,35.0,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/loratadine-and-pseud...
1931,Rhinocort Allergy,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,1%,OTC,B,N,NaN,9.0,1.0,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/rhinocort-allergy.html
1945,Alavert D-12 Hour Allergy and Sinus,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,0%,OTC,B,N,NaN,1.0,1.0,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/alavert-d-12.html
1951,Allergy & Congestion Relief,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,0%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/cons/allergy-congestion-...
1981,Clear-Atadine-D,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,0%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/cons/clear-atadine-d.html
2021,Leader Allergy Relief D-24,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,0%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/leader-allergy-relie...
2024,Loratadine-D 12 Hour,Hayfever,Allergic Rhinitis Other names: Hay Fever; Nasa...,0%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/allergic-rhini...,https://www.drugs.com/mtm/loratadine-d-12-hour...
2905,Aloe Vera Burn Relief Spray with Lidocaine,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/cdi/aloe-vera-burn-relie...
2906,AneCream,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,10.0,1.0,https://www.drugs.com/condition/pain.html,https://www.drugs.com/mtm/anecream.html
2907,Anestacon,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/cons/anestacon-topical-a...
2910,Bactine,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,10.0,1.0,https://www.drugs.com/condition/pain.html,https://www.drugs.com/mtm/bactine.html
2919,diphenhydramine,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/cdi/diphenhydramine-topi...
2929,Itch Relief,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/cdi/itch-relief.html
2937,LMX 4,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/cons/lmx-4-topical-appli...
2938,LMX 5,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/cons/lmx-5-topical-appli...
2941,Medi-Quik Spray,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,10.0,1.0,https://www.drugs.com/condition/pain.html,https://www.drugs.com/mtm/medi-quik-spray.html
2948,RadiaGuard,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/mtm/radiaguard.html
2949,RectiCare,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/mtm/recticare.html
2950,Regenecare HA Spray,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/mtm/regenecare-ha-spray....
2953,Topicaine,Pain,Pain An unpleasant sensory and emotional exper...,1%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/pain.html,https://www.drugs.com/cons/topicaine-topical-a...

In [20]:
filter_const = data['medical_condition'] == 'Constipation'
data_const = data_otc[filter_const]
data_const

/var/folders/kj/8ccbfhn56tgcwgc45d118plh0000gn/T/ipykernel_3419/1055018912.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data_const = data_otc[filter_const]

,drug_name,medical_condition,medical_condition_description,activity,rx_otc,pregnancy_category,csa,alcohol,rating,no_of_reviews,medical_condition_url,drug_link
1080,Dulcolax,Constipation,Constipation Other names: Difficulty passing s...,45%,OTC,B,N,NaN,5.2,960.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/dulcolax.html
1081,bisacodyl,Constipation,Constipation Other names: Difficulty passing s...,32%,OTC,B,N,NaN,5.2,1357.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/bisacodyl-oral-and-r...
1087,Metamucil,Constipation,Constipation Other names: Difficulty passing s...,17%,OTC,N,N,NaN,6.1,28.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/metamucil.html
1090,FiberCon,Constipation,Constipation Other names: Difficulty passing s...,11%,OTC,N,N,NaN,9.0,1.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/fibercon.html
1095,psyllium,Constipation,Constipation Other names: Difficulty passing s...,8%,OTC,N,N,NaN,6.3,30.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/psyllium.html
1099,Bisa-Lax,Constipation,Constipation Other names: Difficulty passing s...,5%,OTC,B,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/cdi/bisa-lax.html
1102,Correctol,Constipation,Constipation Other names: Difficulty passing s...,5%,OTC,B,N,NaN,5.3,36.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/cdi/correctol.html
1104,Fleet Bisacodyl,Constipation,Constipation Other names: Difficulty passing s...,5%,OTC,B,N,NaN,10.0,1.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/cdi/fleet-bisacodyl-enem...
1116,Hydrocil,Constipation,Constipation Other names: Difficulty passing s...,2%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/hydrocil.html
1117,Konsyl,Constipation,Constipation Other names: Difficulty passing s...,2%,OTC,N,N,NaN,9.0,2.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/konsyl.html
1119,Reguloid,Constipation,Constipation Other names: Difficulty passing s...,2%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/reguloid.html
1123,Equalactin,Constipation,Constipation Other names: Difficulty passing s...,1%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/equalactin.html
1125,Fiber Lax,Constipation,Constipation Other names: Difficulty passing s...,1%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/fiber-lax.html
1126,Fiber Laxative,Constipation,Constipation Other names: Difficulty passing s...,1%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/cdi/fiber-laxative.html
1130,Natural Fiber Therapy,Constipation,Constipation Other names: Difficulty passing s...,1%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/natural-fiber-therap...
1134,polycarbophil,Constipation,Constipation Other names: Difficulty passing s...,1%,OTC,N,N,NaN,5.0,3.0,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/polycarbophil.html
1138,castor oil,Constipation,Constipation Other names: Difficulty passing s...,0%,OTC,X,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/monograph/castor-oil.html
1139,Fibertab,Constipation,Constipation Other names: Difficulty passing s...,0%,OTC,N,N,NaN,NaN,NaN,https://www.drugs.com/condition/constipation.html,https://www.drugs.com/mtm/fibertab.html